apiVersion: v1
kind: Namespace
metadata:
  name: syncer
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: syncer

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: syncer-controller
  namespace: syncer
  labels:
    app.kubernetes.io/component: syncer-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: syncer

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: syncer-controller-cluster-admin
  labels:
    app.kubernetes.io/component: syncer-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: syncer
subjects:
  - kind: ServiceAccount
    name: syncer-controller
    namespace: syncer
roleRef:
  kind: ClusterRole
  # TODO: don't require cluster-admin
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncer-controller
  namespace: syncer
  labels:
    app.kubernetes.io/name: syncer-controller
    app.kubernetes.io/component: syncer-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: devel
    app.kubernetes.io/part-of: syncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: syncer-controller
      app.kubernetes.io/component: syncer-controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: syncer
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app.kubernetes.io/name: syncer-controller
        app.kubernetes.io/component: syncer-controller
        app.kubernetes.io/instance: default
        app.kubernetes.io/version: devel
        app.kubernetes.io/part-of: syncer
        app: syncer-controller
    spec:
      serviceAccountName: syncer-controller
      containers:
      - name: syncer-controller
        image: ko://github.com/imjasonh/syncer
