apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: from
spec:
  replicas: 1
  selector:
    matchLabels:
      foo: foo
  template:
    metadata:
      labels:
        foo: foo
    spec:
      containers:
      - name: nginx
        image: nginx
